parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Document,Migrations,Tests,Kernel.php}'

    App\ApiClient\GameResultClient:
        arguments:
            $apiUrl: '%env(API_URL)%'
            $gameResultsUri: '%env(GAME_RESULTS_URI)%'

    App\MessageHandler\UpdateGameResultsHandler:
        arguments:
            $refreshPeriodInSec: '%env(API_REFRESH_PERIOD_IN_SECONDS)%'
